### ISSUE TITLE
Windows 10 

### ISSUE THREAD

**Issue by jbrown215** [cmugpi/cmugpi.github.io#7]
We should consider having specific Windows 10 instructions that use the bash that comes included with Windows 10.

**Comment by jez** [comment]
Oh yeah, that would be cool! I'd only do it if we had someone on course staff who would be comfortable troubleshooting it.

**Comment by jbrown215** [comment]
Andrew brought this up to me. @anbenson -- would you feel comfortable troubleshooting?

**Comment by anbenson** [comment]
Sure, let me know what you want me to do.

**Comment by jez** [comment]
In addition to just writing an entry on the website for how to get things set up, we'd want to make sure that there was always (or nearly always) someone in lecture who can we can direct questions to. If you want to do those things then let's do it.

@anbenson Do you personally use this? Do you think it's a smooth experience?

**Comment by anbenson** [comment]
Nowadays I use Linux more often than Windows, but I've used it and my experience with it is that the environment is near identical to Linux (except X, but an X server can be installed), especially since all students will be doing is using ssh. I'd feel comfortable answering questions in lecture if needed.

I can writeup some instructions and PR if you like.

**Comment by anbenson** [comment]
Commits are in, but I don't have permission to deploy. Can one of you do it? I'm on a plane all of Friday so I won't be able to do it too soon even if you give me permission.

**Comment by jbrown215** [comment]
looks like its deployed. is this ready to close?

**Comment by jez** [comment]
Yeah I deployed this when I made the changes to fix the GPI_PATH stuff in the initial setup.
